baseURL = "https://massageeden.co.nz/"
languageCode = "en-nz"
title = "Massage Eden"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]
timeout = "60s"

[build]
writeStats = true

[module]
  [[module.imports]]
    path = "github.com/MacSmithNZ/tailwind-starter"

[[params.locations]]
name = "Auckland CBD"
URL = "https://g.page/MassageMeAuckland"

[[params.locations]]
name = "Parnell"
URL = "https://g.page/MassageMeParnell"

[[params.locations]]
name = "Rotorua"
URL = "https://goo.gl/maps/vPwYvMsriwtG58ZQ9"

[[menus.social]]
name = "Facebook"
URL = "https://www.facebook.com/MassageEdenNZ"
pre = "facebook-f"

[[menus.social]]
name = "Instagram"
URL = "https://www.instagram.com/massageedennz/"
pre = "instagram"

[[menus.social]]
name = "Tripadvisor"
URL = "https://www.tripadvisor.co.nz/Attraction_Review-g255111-d23542323-Reviews-Massage_Eden_at_the_Pullman-Rotorua_Rotorua_District_Bay_of_Plenty_Region_North_.html"
pre = "tripadvisor"

[params]
logo = "massageeden-logo-icon.png"
bookingLink = "/schedule-an-appointment/"
google_maps_link = "https://maps.google.com/maps?cid=11971744219492874884"
facebook_username = "MassageEdenNZ"
tel_number = "+6473439760"
time_format_default = "Jan 2, 2006"

[params.call_to_action]
no_margin = true
bg_color = "secondary-50"
h2 = "Make massage a part of your routine."
p = "At Massage Eden we make your comfort our top priority. Start today!"
a = "Book an appointment"
a_href = "/schedule-an-appointment/"
a_is_button = true